# Generated by Django 4.1.7 on 2023-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="selling_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
